FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json* ./

RUN npm install 

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production

ARG APP_PORT=8080 
# Default port
ENV PORT=${APP_PORT}

EXPOSE ${APP_PORT}

COPY package.json ./
COPY package-lock.json* ./

RUN npm install --production

COPY --from=builder /app/dist ./dist

CMD ["node", "dist/index.js"]
